# GitHub Actions Workflow
name: .NET CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: sellphonemvcui:${{ github.sha }}
  DOCKER_REGISTRY: docker.io
  DOTNET_VERSION: '9.0' # Match your .NET version from .csproj

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
        continue-on-error: true

  docker-build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./SellPhoneMvcUI/Dockerfile  # Updated path to Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}
          labels: |
            org.opencontainers.image.title=sellphonemvcui
            org.opencontainers.image.version=${{ github.sha }}

# Dockerfile (placed in SellPhoneMvcUI/)
# Giai đoạn build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Sao chép toàn bộ mã nguồn
COPY . ./
RUN ls -la  # Kiểm tra xem tệp .sln và các tệp khác có được sao chép không
RUN if [ ! -f "SellPhoneMvcUI.sln" ]; then echo "ERROR: SellPhoneMvcUI.sln not found!"; exit 1; fi
RUN dotnet restore -v detailed  # Khôi phục gói từ tệp .sln

# Xuất bản ứng dụng
RUN dotnet publish -c Release -o /app/publish
RUN ls -la /app/publish  # Kiểm tra đầu ra publish

# Giai đoạn runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

# Sao chép kết quả từ giai đoạn build
COPY --from=build /app/publish ./

# Cấu hình cổng
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

# Chạy ứng dụng
ENTRYPOINT ["dotnet", "SellPhoneMvcUI.dll"]
